### ISSUE TITLE
Add !SearchTopic 

### ISSUE THREAD

**Issue by Evert-Arends** [Roobarb/hkjl-bot#15] opened 2016-11-15 15:49 UTC
hackenkunjeleren.nl has a lot of tutorials, it would be nice if we could search for those in IRC. 

!Searchtopic 'Wat is hacken' => 'https://www.hackenkunjeleren.nl/introductie-wat-is-hacken-is-deze-site-voor-mij/'

**Comment by Roobarb** [comment] 2016-11-15 16:01
duplicate of https://github.com/Roobarb/hkjl-bot/issues/6

**Closed as completed by Roobarb** 2016-11-15 16:01 UTC
